# Generated by Django 2.0.5 on 2018-05-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reginfo',
            old_name='password',
            new_name='regInfo_password',
        ),
        migrations.RenameField(
            model_name='reginfo',
            old_name='username',
            new_name='regInfo_username',
        ),
        migrations.AlterModelTable(
            name='reginfo',
            table='registration_app',
        ),
    ]
