# Generated by Django 2.0.5 on 2018-06-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='comments',
            name='article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
