# Generated by Django 2.0.5 on 2018-06-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
